name: Test and publish the repo to PyPI on release

on:
  push:
    branches:
      - main

jobs:
  run-tests:
    uses: ./.github/workflows/run-tests.yml

  build:
    uses: ./.github/workflows/build-binary.yml
    needs: run-tests

  release-please:
    needs: build
    runs-on: ubuntu-latest

    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      tag_name: ${{ steps.release.outputs.tag_name }}

    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          release-type: python

  upload-artifact:
    needs: release-please
    runs-on: ubuntu-latest
    strategy:
      matrix:
        artifact_os:
          - ubuntu-latest
          - macos-latest
          - windows-latest

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        if: ${{ needs.release-please.outputs.release_created }}
        with:
          name: build-${{ matrix.artifact_os }}
          path: artifact

      - name: Upload Release Artifact
        if: ${{ needs.release-please.outputs.release_created }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release upload ${{ needs.release-please.outputs.tag_name }} ./artifact/ksem_transformer.exe
